# Students Do: Preventing credit card defaults with neural networks

In this activity, you will train a neural network model to predict whether a credit card holder will default in the next month.

The dataset provided contains `30,000` anonymous records of credit default status with `23` features columns and one binary target column entitled _DEFAULT_, where `1` represents a defaulted credit card.

The `23` features include demographic info (age, gender, marital status, etc.), credit limit, past payment details, and other relevant information.

You are tasked to create a neural network model to predict if a credit card holder will default.

In [1]:
# Initial imports
from path import Path
import pandas as pd
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

%matplotlib inline

## Instructions

1. Load the data in a Pandas DataFrame.

In [3]:
# Read in data
file_path = Path(r'D:\data\neural\cc_default.csv')
df = pd.read_csv(file_path)

df.head()

,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,PAY_5,...,"""BILL_AMT4""",BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,DEFAULT
0,20000,2,2,1,24,2,2,-1,-1,-2,...,0,0,0,0,689,0,0,0,0,1
1,120000,2,2,2,26,-1,2,0,0,0,...,3272,3455,3261,0,1000,1000,1000,0,2000,1
2,90000,2,2,2,34,0,0,0,0,0,...,14331,14948,15549,1518,1500,1000,1000,1000,5000,0
3,50000,2,2,1,37,0,0,0,0,0,...,28314,28959,29547,2000,2019,1200,1100,1069,1000,0
4,50000,1,2,1,57,-1,0,-1,0,0,...,20940,19146,19131,2000,36681,10000,9000,689,679,0

2. Define the features set `X` by including all the columns of the DataFrame except the `DEFAULT` column.

In [4]:
# Define features data

features_df = df.drop(columns = ["DEFAULT"])
features_df.head()

,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,PAY_5,...,BILL_AMT3,"""BILL_AMT4""",BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6
0,20000,2,2,1,24,2,2,-1,-1,-2,...,689,0,0,0,0,689,0,0,0,0
1,120000,2,2,2,26,-1,2,0,0,0,...,2682,3272,3455,3261,0,1000,1000,1000,0,2000
2,90000,2,2,2,34,0,0,0,0,0,...,13559,14331,14948,15549,1518,1500,1000,1000,1000,5000
3,50000,2,2,1,37,0,0,0,0,0,...,49291,28314,28959,29547,2000,2019,1200,1100,1069,1000
4,50000,1,2,1,57,-1,0,-1,0,0,...,35835,20940,19146,19131,2000,36681,10000,9000,689,679

3. Create the target vector `y` by assigning the values of the `DEFAULT` column of the DataFrame.

In [8]:
# Define target data
output_df = df["DEFAULT"].to_frame()
output_df.head()

   DEFAULT
0        1
1        1
2        0
3        0
4        0

4. Create the training an testing sets using the `train_test_split` function from `sklearn`.

In [9]:
# Create training and testing datasets
features_df_train, features_df_test, output_df_train, output_df_test = train_test_split(
    features_df, output_df, random_state=78
)

5. Scale the features data using the `StandardScaler` from `sklearn`.

In [13]:
# Create the scaler instance

features_df_scaler = StandardScaler()

In [14]:
# Fit the scaler

features_df_scaler.fit(features_df_train)

StandardScaler()

In [15]:
# Scale the features data
features_df_train_scaled = features_df_scaler.transform(features_df_train)
features_df_test_scaled = features_df_scaler.transform(features_df_test)

6. Create a neural network model with `23` inputs, one hidden layer with `69` units, and an output layer with a single output. Use the `relu` activation function for the first layer and `sigmoid` for the second layer.

In [17]:
# Define the model
number_inputs = 23
number_hidden_nodes = 69

nn = Sequential()

nn.add(Dense(units=number_hidden_nodes, activation="relu", input_dim=number_inputs))

number_classes = 1

nn.add(Dense(units=number_classes, activation="sigmoid"))

nn.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_2 (Dense)              (None, 69)                1656
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 70
=================================================================
Total params: 1,726
Trainable params: 1,726
Non-trainable params: 0
_________________________________________________________________

7. Compile the neural network model using the `binary_crossentropy` loss function, the `adam` optimizer, and `accuracy` as additional metric.

In [18]:
# Compile model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

8. Fit the model with `100` epochs.

In [19]:
# Fit the model
model_cc = nn.fit(features_df_train_scaled, output_df_train, epochs=100)

Epoch 1/100
704/704 [==============================] - 1s 970us/step - loss: 0.5415 - accuracy: 0.7509
Epoch 2/100
704/704 [==============================] - 1s 859us/step - loss: 0.4494 - accuracy: 0.8155
Epoch 3/100
704/704 [==============================] - 1s 922us/step - loss: 0.4514 - accuracy: 0.8114
Epoch 4/100
704/704 [==============================] - 1s 983us/step - loss: 0.4477 - accuracy: 0.8108
Epoch 5/100
704/704 [==============================] - 1s 896us/step - loss: 0.4431 - accuracy: 0.8121
Epoch 6/100
704/704 [==============================] - 1s 919us/step - loss: 0.4373 - accuracy: 0.8169
Epoch 7/100
704/704 [==============================] - 1s 891us/step - loss: 0.4324 - accuracy: 0.8208
Epoch 8/100
704/704 [==============================] - 1s 988us/step - loss: 0.4317 - accuracy: 0.8225
Epoch 9/100
704/704 [==============================] - 1s 969us/step - loss: 0.4380 - accuracy: 0.8162
Epoch 10/100
704/704 [==============================] - 1s 899us/step - loss: 0.4291 - accuracy: 0.8215
Epoch 11/100
704/704 [==============================] - 1s 929us/step - loss: 0.4314 - accuracy: 0.8202
Epoch 12/100
704/704 [==============================] - 1s 1ms/step - loss: 0.4339 - accuracy: 0.8166
Epoch 13/100
704/704 [==============================] - 1s 929us/step - loss: 0.4183 - accuracy: 0.8235
Epoch 14/100
704/704 [==============================] - 1s 902us/step - loss: 0.4246 - accuracy: 0.8229
Epoch 15/100
704/704 [==============================] - 1s 962us/step - loss: 0.4252 - accuracy: 0.8232
Epoch 16/100
704/704 [==============================] - 1s 1ms/step - loss: 0.4263 - accuracy: 0.8206
Epoch 17/100
704/704 [==============================] - 1s 1ms/step - loss: 0.4225 - accuracy: 0.8266
Epoch 18/100
704/704 [==============================] - 1s 872us/step - loss: 0.4246 - accuracy: 0.8222
Epoch 19/100
704/704 [==============================] - 1s 1ms/step - loss: 0.4260 - accuracy: 0.8204
Epoch 20/100
704/704 [==============================] - 1s 1ms/step - loss: 0.4263 - accuracy: 0.8195: 0s
Epoch 21/100
704/704 [==============================] - 1s 1ms/step - loss: 0.4283 - accuracy: 0.8194
Epoch 22/100
704/704 [==============================] - 1s 1ms/step - loss: 0.4262 - accuracy: 0.8209
Epoch 23/100
704/704 [==============================] - 1s 1ms/step - loss: 0.4318 - accuracy: 0.8167
Epoch 24/100
704/704 [==============================] - 1s 843us/step - loss: 0.4177 - accuracy: 0.8232
Epoch 25/100
704/704 [==============================] - 1s 845us/step - loss: 0.4229 - accuracy: 0.8205
Epoch 26/100
704/704 [==============================] - 1s 907us/step - loss: 0.4283 - accuracy: 0.8168
Epoch 27/100
704/704 [==============================] - 1s 997us/step - loss: 0.4214 - accuracy: 0.8229
Epoch 28/100
704/704 [==============================] - 1s 991us/step - loss: 0.4250 - accuracy: 0.8198
Epoch 29/100
704/704 [==============================] - 1s 866us/step - loss: 0.4250 - accuracy: 0.8185
Epoch 30/100
704/704 [==============================] - 1s 925us/step - loss: 0.4243 - accuracy: 0.8214
Epoch 31/100
704/704 [==============================] - 1s 1ms/step - loss: 0.4147 - accuracy: 0.8270
Epoch 32/100
704/704 [==============================] - 1s 862us/step - loss: 0.4150 - accuracy: 0.8252
Epoch 33/100
704/704 [==============================] - 1s 907us/step - loss: 0.4206 - accuracy: 0.8241
Epoch 34/100
704/704 [==============================] - 1s 881us/step - loss: 0.4145 - accuracy: 0.8258
Epoch 35/100
704/704 [==============================] - 1s 950us/step - loss: 0.4157 - accuracy: 0.8254
Epoch 36/100
704/704 [==============================] - 1s 1ms/step - loss: 0.4161 - accuracy: 0.8263
Epoch 37/100
704/704 [==============================] - 1s 881us/step - loss: 0.4112 - accuracy: 0.8296
Epoch 38/100
704/704 [==============================] - 1s 903us/step - loss: 0.4153 - accuracy: 0.8236
Epoch 39/100
704/704 [==============================] - 1s 987us/step - loss: 0.4126 - accuracy: 0.8265
Epoch 40/100
704/704 [==============================] - 1s 903us/step - loss: 0.4184 - accuracy: 0.8234
Epoch 41/100
704/704 [==============================] - 1s 916us/step - loss: 0.4194 - accuracy: 0.8223
Epoch 42/100
704/704 [==============================] - 1s 916us/step - loss: 0.4172 - accuracy: 0.8217
Epoch 43/100
704/704 [==============================] - 1s 944us/step - loss: 0.4198 - accuracy: 0.8200
Epoch 44/100
704/704 [==============================] - 1s 1ms/step - loss: 0.4175 - accuracy: 0.8234
Epoch 45/100
704/704 [==============================] - 1s 862us/step - loss: 0.4190 - accuracy: 0.8199
Epoch 46/100
704/704 [==============================] - 1s 977us/step - loss: 0.4142 - accuracy: 0.8260
Epoch 47/100
704/704 [==============================] - 1s 889us/step - loss: 0.4148 - accuracy: 0.8246
Epoch 48/100
704/704 [==============================] - 1s 983us/step - loss: 0.4209 - accuracy: 0.82140s - loss: 0
Epoch 49/100
704/704 [==============================] - 1s 920us/step - loss: 0.4164 - accuracy: 0.8245
Epoch 50/100
704/704 [==============================] - 1s 849us/step - loss: 0.4101 - accuracy: 0.8278
Epoch 51/100
704/704 [==============================] - 1s 977us/step - loss: 0.4183 - accuracy: 0.8202
Epoch 52/100
704/704 [==============================] - 1s 1ms/step - loss: 0.4157 - accuracy: 0.8235
Epoch 53/100
704/704 [==============================] - 1s 1ms/step - loss: 0.4174 - accuracy: 0.8208
Epoch 54/100
704/704 [==============================] - 1s 1ms/step - loss: 0.4166 - accuracy: 0.8234
Epoch 55/100
704/704 [==============================] - 1s 1ms/step - loss: 0.4140 - accuracy: 0.8251
Epoch 56/100
704/704 [==============================] - 1s 993us/step - loss: 0.4127 - accuracy: 0.8250
Epoch 57/100
704/704 [==============================] - 1s 863us/step - loss: 0.4080 - accuracy: 0.8256
Epoch 58/100
704/704 [==============================] - 1s 958us/step - loss: 0.4159 - accuracy: 0.8239
Epoch 59/100
704/704 [==============================] - 1s 832us/step - loss: 0.4140 - accuracy: 0.8236
Epoch 60/100
704/704 [==============================] - 1s 1ms/step - loss: 0.4094 - accuracy: 0.8272
Epoch 61/100
704/704 [==============================] - 1s 916us/step - loss: 0.4110 - accuracy: 0.8253
Epoch 62/100
704/704 [==============================] - 1s 880us/step - loss: 0.4070 - accuracy: 0.8261
Epoch 63/100
704/704 [==============================] - 1s 953us/step - loss: 0.4146 - accuracy: 0.8218
Epoch 64/100
704/704 [==============================] - 1s 996us/step - loss: 0.4087 - accuracy: 0.8250
Epoch 65/100
704/704 [==============================] - 1s 902us/step - loss: 0.4078 - accuracy: 0.8267
Epoch 66/100
704/704 [==============================] - 1s 896us/step - loss: 0.4146 - accuracy: 0.8219
Epoch 67/100
704/704 [==============================] - 1s 894us/step - loss: 0.4064 - accuracy: 0.82710s - loss: 0
Epoch 68/100
704/704 [==============================] - 1s 1ms/step - loss: 0.4099 - accuracy: 0.8252
Epoch 69/100
704/704 [==============================] - 1s 1ms/step - loss: 0.4029 - accuracy: 0.8301
Epoch 70/100
704/704 [==============================] - 1s 953us/step - loss: 0.4093 - accuracy: 0.8285
Epoch 71/100
704/704 [==============================] - 1s 934us/step - loss: 0.4190 - accuracy: 0.8216
Epoch 72/100
704/704 [==============================] - 1s 1ms/step - loss: 0.4082 - accuracy: 0.8242
Epoch 73/100
704/704 [==============================] - 1s 1ms/step - loss: 0.4109 - accuracy: 0.8260
Epoch 74/100
704/704 [==============================] - 1s 1ms/step - loss: 0.4089 - accuracy: 0.8255
Epoch 75/100
704/704 [==============================] - 1s 1ms/step - loss: 0.4053 - accuracy: 0.8273
Epoch 76/100
704/704 [==============================] - 1s 1ms/step - loss: 0.4032 - accuracy: 0.8296
Epoch 77/100
704/704 [==============================] - 1s 855us/step - loss: 0.4046 - accuracy: 0.8275
Epoch 78/100
704/704 [==============================] - 1s 942us/step - loss: 0.4049 - accuracy: 0.82640s - loss: 0.4044 - accuracy
Epoch 79/100
704/704 [==============================] - 1s 990us/step - loss: 0.4034 - accuracy: 0.8301
Epoch 80/100
704/704 [==============================] - 1s 879us/step - loss: 0.4054 - accuracy: 0.8267
Epoch 81/100
704/704 [==============================] - 1s 914us/step - loss: 0.4072 - accuracy: 0.8272
Epoch 82/100
704/704 [==============================] - 1s 879us/step - loss: 0.4078 - accuracy: 0.8283
Epoch 83/100
704/704 [==============================] - 1s 883us/step - loss: 0.4023 - accuracy: 0.8291
Epoch 84/100
704/704 [==============================] - 1s 1ms/step - loss: 0.4084 - accuracy: 0.8256
Epoch 85/100
704/704 [==============================] - 1s 885us/step - loss: 0.4107 - accuracy: 0.8264
Epoch 86/100
704/704 [==============================] - 1s 954us/step - loss: 0.4070 - accuracy: 0.8277
Epoch 87/100
704/704 [==============================] - 1s 950us/step - loss: 0.4095 - accuracy: 0.8245
Epoch 88/100
704/704 [==============================] - 1s 953us/step - loss: 0.4012 - accuracy: 0.8322
Epoch 89/100
704/704 [==============================] - 1s 861us/step - loss: 0.4071 - accuracy: 0.8267
Epoch 90/100
704/704 [==============================] - 1s 862us/step - loss: 0.4019 - accuracy: 0.8273
Epoch 91/100
704/704 [==============================] - 1s 930us/step - loss: 0.4039 - accuracy: 0.8303
Epoch 92/100
704/704 [==============================] - 1s 955us/step - loss: 0.4017 - accuracy: 0.8302
Epoch 93/100
704/704 [==============================] - 1s 992us/step - loss: 0.4038 - accuracy: 0.8259
Epoch 94/100
704/704 [==============================] - 1s 861us/step - loss: 0.4039 - accuracy: 0.8286
Epoch 95/100
704/704 [==============================] - 1s 882us/step - loss: 0.4013 - accuracy: 0.8298
Epoch 96/100
704/704 [==============================] - 1s 1ms/step - loss: 0.3995 - accuracy: 0.8287
Epoch 97/100
704/704 [==============================] - 1s 857us/step - loss: 0.4099 - accuracy: 0.8216
Epoch 98/100
704/704 [==============================] - 1s 904us/step - loss: 0.4027 - accuracy: 0.8298
Epoch 99/100
704/704 [==============================] - 1s 860us/step - loss: 0.4037 - accuracy: 0.8301
Epoch 100/100
704/704 [==============================] - 1s 836us/step - loss: 0.4059 - accuracy: 0.8278

9. Plot the loss function and accuracy.

In [ ]:
# Create a DataFrame with the history dictionary


# Plot the loss

In [ ]:
# Plot the accuracy

10. Evaluate the model using testing data and the `evaluate` method.

In [ ]:
# Evaluate the model fit with linear dummy data

## Challenge

For this challenge section, you have to figure out how the model you created could be modified to improve the accuracy.

1. Review the Keras documentation about activation functions, and decide if there is anyone that could be used instead of `sigmoid`.

2. Add a second hidden layer with `69` units and use a different activation function than `sigmoid`.

3. Change any other parameter that you believe could improve the model's accuracy.

4. Evaluate the model's accuracy and loss and write down your conclusions.

In [ ]:
# Define the model

In [ ]:
# Compile model

In [ ]:
# Fit the model

In [ ]:
# Evaluate the model fit with linear dummy data

### Conclusions

**Your Answer Here**